"""Dynamic nginx proxy configuration generator.

When a new agent container is spawned, generates an nginx config file
for the user's subdomain and reloads nginx.

Example: user "abc123" gets abc123.agents.devpunks.io → localhost:9105
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path

import structlog

log = structlog.get_logger()

NGINX_TEMPLATE_SSL = """# Auto-generated by orchestrator for user {user_id}
server {{
    listen 80;
    server_name {subdomain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl;
    server_name {subdomain};

    ssl_certificate {ssl_cert_path};
    ssl_certificate_key {ssl_key_path};

    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 300s;
    }}
}}
"""

NGINX_TEMPLATE_HTTP = """# Auto-generated by orchestrator for user {user_id}
server {{
    listen 80;
    server_name {subdomain};

    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 300s;
    }}
}}
"""


class NginxProxy:
    """Manage dynamic nginx proxy configurations."""

    def __init__(
        self,
        conf_dir: str = "/etc/nginx/conf.d/agents",
        domain: str = "agents.devpunks.io",
        ssl_cert_path: str = "",
        ssl_key_path: str = "",
    ):
        self.conf_dir = Path(conf_dir)
        self.domain = domain
        self.ssl_cert_path = ssl_cert_path
        self.ssl_key_path = ssl_key_path

    async def add_proxy(self, user_id: str, port: int) -> str:
        """Add nginx proxy config for a user's agent.

        Args:
            user_id: User identifier (used as subdomain prefix).
            port: Local port the agent container is listening on.

        Returns:
            The subdomain URL.
        """
        subdomain = f"{user_id}.{self.domain}"
        conf_path = self.conf_dir / f"{user_id}.conf"

        # Use SSL template if cert paths are configured
        if self.ssl_cert_path and self.ssl_key_path:
            config = NGINX_TEMPLATE_SSL.format(
                user_id=user_id,
                subdomain=subdomain,
                port=port,
                ssl_cert_path=self.ssl_cert_path,
                ssl_key_path=self.ssl_key_path,
            )
        else:
            config = NGINX_TEMPLATE_HTTP.format(
                user_id=user_id,
                subdomain=subdomain,
                port=port,
            )

        # Write config file
        self.conf_dir.mkdir(parents=True, exist_ok=True)
        conf_path.write_text(config)

        log.info("nginx_config_written", user_id=user_id, path=str(conf_path))

        # Reload nginx
        await self._reload_nginx()

        return f"https://{subdomain}"

    async def remove_proxy(self, user_id: str) -> None:
        """Remove nginx proxy config for a user's agent."""
        conf_path = self.conf_dir / f"{user_id}.conf"

        if conf_path.exists():
            conf_path.unlink()
            log.info("nginx_config_removed", user_id=user_id)
            await self._reload_nginx()

    async def _reload_nginx(self) -> bool:
        """Reload nginx configuration."""
        try:
            proc = await asyncio.create_subprocess_exec(
                "nginx", "-s", "reload",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await proc.communicate()

            if proc.returncode == 0:
                log.info("nginx_reloaded")
                return True
            else:
                log.error("nginx_reload_failed", stderr=stderr.decode()[:200])
                return False
        except FileNotFoundError:
            log.warning("nginx_not_found_skip_reload")
            return False
        except Exception as e:
            log.error("nginx_reload_error", error=str(e))
            return False

    def get_subdomain(self, user_id: str) -> str:
        """Get the subdomain URL for a user."""
        return f"https://{user_id}.{self.domain}"
