"""Dynamic nginx proxy configuration generator.

When a new agent container is spawned, generates an nginx config file
for the user's subdomain and reloads nginx.

Example: user "abc123" gets abc123.agents.devpunks.io → localhost:9105
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path

import structlog

log = structlog.get_logger()

NGINX_TEMPLATE_SSL = """# Auto-generated by orchestrator for user {user_id}
server {{
    listen 80;
    server_name {subdomain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl;
    server_name {subdomain};

    ssl_certificate {ssl_cert_path};
    ssl_certificate_key {ssl_key_path};

    # Orchestrator API (auth, agent management)
    location /orch/ {{
        proxy_pass http://127.0.0.1:{orch_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

    # Everything: agent API, SPA at /app, A2A JSON-RPC (POST /), profile, WebSocket
    # The agent backend handles routing: GET / → profile, POST / → A2A
    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 300s;
    }}
}}
"""

NGINX_TEMPLATE_HTTP = """# Auto-generated by orchestrator for user {user_id}
server {{
    listen 80;
    server_name {subdomain};

    # Orchestrator API (auth, agent management)
    location /orch/ {{
        proxy_pass http://127.0.0.1:{orch_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}

    # Everything: agent API, SPA at /app, A2A JSON-RPC (POST /), profile, WebSocket
    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 300s;
    }}
}}
"""


class NginxProxy:
    """Manage dynamic nginx proxy configurations."""

    def __init__(
        self,
        conf_dir: str = "/etc/nginx/conf.d/agents",
        domain: str = "agents.devpunks.io",
        ssl_cert_path: str = "",
        ssl_key_path: str = "",
        orch_port: int = 8002,
    ):
        self.conf_dir = Path(conf_dir)
        self.domain = domain
        self.ssl_cert_path = ssl_cert_path
        self.ssl_key_path = ssl_key_path
        self.orch_port = orch_port

    async def add_proxy(self, subdomain_prefix: str, port: int) -> str:
        """Add nginx proxy config for a user's agent.

        Args:
            subdomain_prefix: Subdomain name (e.g. "gandalf", "morpheus").
            port: Local port the agent container is listening on.

        Returns:
            The full subdomain URL.
        """
        subdomain = f"{subdomain_prefix}.{self.domain}"
        conf_path = self.conf_dir / f"{subdomain_prefix}.conf"

        # Use SSL template if cert paths are configured
        if self.ssl_cert_path and self.ssl_key_path:
            config = NGINX_TEMPLATE_SSL.format(
                user_id=subdomain_prefix,
                subdomain=subdomain,
                port=port,
                orch_port=self.orch_port,
                ssl_cert_path=self.ssl_cert_path,
                ssl_key_path=self.ssl_key_path,
            )
        else:
            config = NGINX_TEMPLATE_HTTP.format(
                user_id=subdomain_prefix,
                subdomain=subdomain,
                port=port,
                orch_port=self.orch_port,
            )

        # Write config file
        self.conf_dir.mkdir(parents=True, exist_ok=True)
        conf_path.write_text(config)

        log.info("nginx_config_written", subdomain=subdomain_prefix, path=str(conf_path))

        # Reload nginx
        await self._reload_nginx()

        return f"https://{subdomain}"

    async def remove_proxy(self, subdomain_prefix: str) -> None:
        """Remove nginx proxy config for a user's agent."""
        conf_path = self.conf_dir / f"{subdomain_prefix}.conf"

        if conf_path.exists():
            conf_path.unlink()
            log.info("nginx_config_removed", subdomain=subdomain_prefix)
            await self._reload_nginx()

    async def _reload_nginx(self) -> bool:
        """Reload nginx on the host.

        Tries multiple strategies:
        1. Direct `nginx -s reload` (works if running on host or nginx in PATH)
        2. Docker: run nginx reload in a temporary container with host PID/network
        3. nsenter via PID 1 to reach host namespace (works with --pid=host)
        """
        # Strategy 1: direct nginx command
        try:
            proc = await asyncio.create_subprocess_exec(
                "nginx", "-s", "reload",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await proc.communicate()
            if proc.returncode == 0:
                log.info("nginx_reloaded", method="direct")
                return True
            log.debug("nginx_direct_failed", stderr=stderr.decode()[:200])
        except FileNotFoundError:
            pass

        # Strategy 2: nsenter via PID 1 (requires --pid=host on container)
        try:
            proc = await asyncio.create_subprocess_exec(
                "nsenter", "-t", "1", "-m", "-u", "-i", "-n", "-p",
                "--", "nginx", "-s", "reload",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await proc.communicate()
            if proc.returncode == 0:
                log.info("nginx_reloaded", method="nsenter")
                return True
            log.debug("nginx_nsenter_failed", stderr=stderr.decode()[:200])
        except FileNotFoundError:
            pass

        log.warning("nginx_reload_all_methods_failed")
        return False

    def get_subdomain(self, subdomain_prefix: str) -> str:
        """Get the full subdomain URL."""
        return f"https://{subdomain_prefix}.{self.domain}"
